name: CI/CD Pipeline

on:
  push:
    branches:
      - main # La pipeline s'exécute uniquement sur la branche "main"

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Configurer SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Étape 3 : Se connecter au serveur et déployer
      - name: Deploy Application
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          WORK_DIR: ${{ secrets.WORK_DIR }}
        run: |
          ssh $SSH_USER@$SSH_HOST "
            cd $WORK_DIR &&
            git pull origin main &&
            docker-compose down &&
            docker-compose up --build -d
          "

      # Étape 4 : Nettoyer les fichiers SSH
      - name: Cleanup SSH
        run: rm -rf ~/.ssh
